# Generated by Django 3.2.9 on 2022-01-06 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
